const STORE='nexo_v1_last';
const $=id=>document.getElementById(id);
let game=null,zone=0,person=0,item=0,selected=null,timer=null;
const safe={set(k,v){try{localStorage.setItem(k,v)}catch{}},get(k){try{return localStorage.getItem(k)}catch{return null}},del(k){try{localStorage.removeItem(k)}catch{}}};
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('on'));$(id).classList.add('on');window.scrollTo(0,0)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('on');setTimeout(()=>$('toast').classList.remove('on'),1400)}
function buzz(ms=12){if(navigator.vibrate)navigator.vibrate(ms)}
function tone(){return document.querySelector('input[name=tone]:checked')?.value||'play'}
function start(){game={names:[$('nameA').value.trim()||'Persona A',$('nameB').value.trim()||'Persona B'],tone:tone(),answers:[Array.from({length:6},()=>[null,null,null]),Array.from({length:6},()=>[null,null,null])],started:Date.now()};zone=0;person=0;item=0;save();handoff()}
function save(){if(game)safe.set(STORE,JSON.stringify({game,zone,person,item}))}
function handoff(){const z=ZONES[zone];$('handoffGlyph').textContent=z.icon;$('handoffZone').textContent=z.name;$('handoffTitle').textContent=`Turno de ${game.names[person]}`;$('handoffText').textContent=person===0?`Tres tarjetas privadas sobre ${z.name.toLowerCase()}. Después pasa el teléfono a ${game.names[1]}.`:`Ahora responde ${game.names[1]}. ${game.names[0]}: mirar la pantalla sería técnicamente hacer trampa, aunque la humanidad haya sobrevivido a cosas peores.`;show('handoff')}
function beginCards(){item=0;selected=null;renderCard();show('play')}
function renderCard(){const z=ZONES[zone],it=z.items[item];$('zoneLabel').textContent=`${z.icon} ${z.name}`;$('playerLabel').textContent=game.names[person];$('itemLabel').textContent=`${item+1} / 3`;$('promptIcon').textContent=z.icon;$('prompt').textContent=it[0];$('promptHint').textContent=game.tone==='deep'?it[1]:shortHint(it[1]);$('progress').style.width=`${((zone*6)+(person*3)+item+1)/36*100}%`;selected=game.answers[person][zone][item];document.querySelectorAll('.choice').forEach(b=>b.classList.toggle('on',Number(b.dataset.score)===selected));$('answerNext').disabled=selected===null}
function shortHint(h){return h.replace(/Los seres humanos[^.]*\./,'').replace(/La noble tradición[^.]*\./,'').trim()||'Responde por cómo se siente hoy, no por cómo “debería” sentirse.'}
function choose(score){selected=score;game.answers[person][zone][item]=score;document.querySelectorAll('.choice').forEach(b=>b.classList.toggle('on',Number(b.dataset.score)===score));$('answerNext').disabled=false;buzz()}
function pass(){selected=-1;game.answers[person][zone][item]=-1;nextCard()}
function nextCard(){save();if(item<2){item++;renderCard();return}if(person===0){person=1;item=0;handoff();return}revealZone()}
function valid(arr){return arr.filter(x=>typeof x==='number'&&x>=0)}
function zoneScore(p,z){const v=valid(game.answers[p][z]);return v.length?Math.round(v.reduce((a,b)=>a+b,0)/(v.length*3)*100):null}
function labelScore(v){if(v===null)return 'Sin datos';if(v<26)return 'Puerta protegida';if(v<51)return 'Se abre con contexto';if(v<76)return 'Bastante abierto';return 'Puerta abierta'}
function bridgeFor(z){const a=game.answers[0][z],b=game.answers[1][z];let best=-1,d=-1;for(let i=0;i<3;i++){if(a[i]>=0&&b[i]>=0&&Math.abs(a[i]-b[i])>d){d=Math.abs(a[i]-b[i]);best=i}}const pool=ZONES[z].bridge;if(game.tone==='deep'&&best>=0&&d>=1){return `En la tarjeta “${ZONES[z].items[best][0]}” respondieron distinto. ${pool[1]}`};return d===0?`Aquí estuvieron bastante alineados. ${pool[0]}`:pool[d>=2?1:0]}
function revealZone(){const z=ZONES[zone],a=zoneScore(0,zone),b=zoneScore(1,zone);$('revealIcon').textContent=z.icon;$('revealZone').textContent=z.name;$('revealSub').textContent=z.desc;$('scoreA').textContent=a===null?'—':a;$('scoreB').textContent=b===null?'—':b;$('scoreAName').textContent=`${game.names[0]} · ${labelScore(a)}`;$('scoreBName').textContent=`${game.names[1]} · ${labelScore(b)}`;$('barA').style.width=`${a||0}%`;$('barB').style.width=`${b||0}%`;let badges=[];if(a!==null&&b!==null){let diff=Math.abs(a-b);badges.push(diff<=15?'Ritmo parecido':diff<=35?'Aperturas distintas':'Contraste fuerte');let avg=(a+b)/2;badges.push(avg>=70?'Territorio abierto':avg<35?'Zona protegida':'Zona intermedia')}else badges.push('Alguien prefirió pasar');$('badges').innerHTML=badges.map(x=>`<span class="badge">${x}</span>`).join('');$('bridgeText').textContent=bridgeFor(zone);$('nextZone').textContent=zone===5?'Ver mapa final':'Siguiente territorio';$('countdown').style.display='none';clearInterval(timer);show('reveal');save();buzz(22)}
function nextZone(){if(zone===5){finalize();return}zone++;person=0;item=0;handoff()}
function talk60(){clearInterval(timer);let t=60;$('countdown').style.display='block';$('countdown').textContent='01:00';$('talk60').disabled=true;timer=setInterval(()=>{t--;$('countdown').textContent=`00:${String(t).padStart(2,'0')}`;if(t<=0){clearInterval(timer);$('talk60').disabled=false;$('countdown').textContent='00:00';buzz(40)}},1000)}
function coords(values,cx,cy,r){return values.map((v,i)=>{const ang=-Math.PI/2+i*Math.PI/3,rr=r*((v??0)/100);return [cx+Math.cos(ang)*rr,cy+Math.sin(ang)*rr]})}
function pts(arr){return arr.map(p=>p.map(n=>n.toFixed(1)).join(',')).join(' ')}
function drawRadar(){const A=ZONES.map((_,i)=>zoneScore(0,i)??0),B=ZONES.map((_,i)=>zoneScore(1,i)??0),cx=210,cy=188,r=130;let svg='';for(let ring=1;ring<=4;ring++){const vals=Array(6).fill(ring*25);svg+=`<polygon points="${pts(coords(vals,cx,cy,r))}" fill="none" stroke="#252525" stroke-width="1"/>`}for(let i=0;i<6;i++){const ang=-Math.PI/2+i*Math.PI/3,x=cx+Math.cos(ang)*r,y=cy+Math.sin(ang)*r,lx=cx+Math.cos(ang)*(r+30),ly=cy+Math.sin(ang)*(r+30);svg+=`<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#242424"/><text x="${lx}" y="${ly}" fill="#938d84" font-size="11" text-anchor="middle" dominant-baseline="middle">${ZONES[i].name}</text>`}svg+=`<polygon points="${pts(coords(A,cx,cy,r))}" fill="rgba(215,183,131,.12)" stroke="#d7b783" stroke-width="2"/>`;svg+=`<polygon points="${pts(coords(B,cx,cy,r))}" fill="rgba(158,178,189,.09)" stroke="#9eb2bd" stroke-width="2"/>`;$('radar').innerHTML=svg;$('legendA').textContent=game.names[0];$('legendB').textContent=game.names[1]}
function finalInsights(){const rows=ZONES.map((z,i)=>{const a=zoneScore(0,i),b=zoneScore(1,i);return{z,a,b,avg:(a===null||b===null)?-1:(a+b)/2,diff:(a===null||b===null)?-1:Math.abs(a-b)}});const comparable=rows.filter(x=>x.avg>=0);if(!comparable.length)return[];const open=[...comparable].sort((x,y)=>y.avg-x.avg)[0],contrast=[...comparable].sort((x,y)=>y.diff-x.diff)[0],protected=[...comparable].sort((x,y)=>x.avg-y.avg)[0];return[{k:'Territorio más abierto',v:`${open.z.icon} ${open.z.name}`},{k:'Mayor contraste',v:`${contrast.z.icon} ${contrast.z.name}`},{k:'Zona más protegida',v:`${protected.z.icon} ${protected.z.name}`} ]}
function deckCards(){const rows=ZONES.map((z,i)=>({i,z,a:zoneScore(0,i),b:zoneScore(1,i)})).filter(x=>x.a!==null&&x.b!==null);rows.sort((x,y)=>Math.abs(y.a-y.b)-Math.abs(x.a-x.b));let picks=rows.slice(0,2);let low=[...rows].sort((x,y)=>(x.a+x.b)-(y.a+y.b))[0];if(low&&!picks.some(x=>x.i===low.i))picks.push(low);while(picks.length<3&&rows[picks.length])picks.push(rows[picks.length]);return picks.slice(0,3).map((x,j)=>({label:j===0?'Donde miran distinto':j===1?'Otra puerta':'Para abrir con calma',text:x.z.bridge[j%2]}))}
function finalize(){safe.del(STORE);drawRadar();$('finalIntro').textContent=`${game.names[0]} y ${game.names[1]} no obtuvieron una nota. Obtuvieron algo bastante más útil: dónde la cercanía parece fácil y dónde cada uno necesita un ritmo distinto.`;$('insights').innerHTML=finalInsights().map(x=>`<div class="insight"><small>${x.k}</small><b>${x.v}</b></div>`).join('');$('deck').innerHTML=deckCards().map(c=>`<div class="deck-card"><small>${c.label}</small><p>${c.text}</p></div>`).join('');show('final');buzz(35)}
function share(){const text=`NEXO · Mapa de intimidad\n${game.names[0]} × ${game.names[1]}\n${finalInsights().map(x=>`${x.k}: ${x.v}`).join('\n')}\n\nNo es un test clínico: es un mapa para conversar.`;if(navigator.share){navigator.share({title:'NEXO · Mapa de intimidad',text}).catch(()=>{})}else{navigator.clipboard?.writeText(text);toast('Resumen copiado')}}
document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(Number(b.dataset.score)));$('start').onclick=start;$('handoffGo').onclick=beginCards;$('answerNext').onclick=nextCard;$('pass').onclick=pass;$('nextZone').onclick=nextZone;$('talk60').onclick=talk60;$('restart').onclick=()=>{game=null;zone=0;person=0;item=0;show('home')};$('share').onclick=share;window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});